[2024-09-12 21:43:44,185] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-12 21:43:47,371] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-10-1/mb16.json Launching profiler...
[2024-09-12 21:43:49,240] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:43:52,517] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 10, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:43:54,759] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 21:43:55,694] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 21:44:19,416] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 21:44:21,945] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 21:44:21,945] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-12 21:44:27,335] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-12 21:44:32,029] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 21:44:32,624] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 21:44:32,624] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 21:44:32,625] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 21:44:32,625] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 21:44:32,625] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 10 nodes latency
[2024-09-12 21:44:32,929] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 21:44:32,929] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 21:44:34,200] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220', '172.21.0.47:2221']
[2024-09-12 21:44:34,200] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 21:44:36,088] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:44:39,254] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 21:44:39,255] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:44:41,140] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 21:44:42,405] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 10)
min_nodes: 2, max_nodes: 10, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:13] with 1 devices
StageExecutionResult[14:19] with 1 devices
StageExecutionResult[20:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:9] with 1 devices
StageExecutionResult[10:13] with 1 devices
StageExecutionResult[14:17] with 1 devices
StageExecutionResult[18:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:11] with 1 devices
StageExecutionResult[12:14] with 1 devices
StageExecutionResult[15:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:17] with 1 devices
StageExecutionResult[18:20] with 1 devices
StageExecutionResult[21:22] with 1 devices
StageExecutionResult[23:24] with 1 devices
StageExecutionResult[25:25] with 1 devices
[2024-09-12 21:44:44,188] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 21:44:44,188] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9]}
[2024-09-12 21:44:44,188] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 10, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8], '172.21.0.47:2221': [9]}
[2024-09-12 21:44:44,189] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 35675
[2024-09-12 21:44:44,189] [INFO] [agent.py:232:forward_worker_port] Received worker port: 35675 from worker. Forwarding it to master...
[2024-09-12 21:44:44,191] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 21:44:44,191] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 35675 from master
[2024-09-12 21:44:44,264] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 21:44:44,264] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-12 21:44:44,264] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 21:44:44,362] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:44,599] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:44,830] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:45,027] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
The objective value 2.5059E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:45,671] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:46,006] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:46,281] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:44:46,568] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 21:44:46,917] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.2nodes> pipelines (b: 2)
2 x <oobleck.PipelineTemplate.4nodes> pipelines (b: 31)
B: 64
dataloader: mbs 16
[2024-09-12 21:45:01,064] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 21:45:01,064] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.0030264854431152344, forward time: 1.6667208671569824, backward time: 3.1954147815704346
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 0 done
[2024-09-12 21:45:47,498] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 46433.18
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-12 21:45:47,499] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 8.6410 GB | cache_allocated: 10.3281 GB | max_cache_allocated: 10.3281 GB
step: 1
step in try: 1
load_mbs: 0.0014064311981201172, forward time: 1.240422248840332, backward time: 3.2439868450164795
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 1 done
[2024-09-12 21:46:29,254] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 41754.43
[2024-09-12 21:46:29,255] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 13.3828 GB | max_cache_allocated: 14.1562 GB
step: 2
step in try: 2
load_mbs: 0.0016779899597167969, forward time: 1.24058198928833, backward time: 3.1990408897399902
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 2 done
[2024-09-12 21:47:12,147] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 42891.25
[2024-09-12 21:47:12,148] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 3
step in try: 3
load_mbs: 0.0017821788787841797, forward time: 1.241774559020996, backward time: 3.203073740005493
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 3 done
[2024-09-12 21:48:15,647] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 63499.31
[2024-09-12 21:48:15,649] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 4
step in try: 4
load_mbs: 0.0016956329345703125, forward time: 1.2416496276855469, backward time: 3.1980082988739014
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 4 done
[2024-09-12 21:49:27,677] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 72028.23
[2024-09-12 21:49:27,680] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 5
step in try: 5
load_mbs: 0.0019664764404296875, forward time: 1.2396762371063232, backward time: 3.19663143157959
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 5 done
[2024-09-12 21:50:42,709] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 75029.55
[2024-09-12 21:50:42,711] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 6
step in try: 6
load_mbs: 0.0016345977783203125, forward time: 1.2392573356628418, backward time: 3.1927168369293213
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 6 done
[2024-09-12 21:52:00,627] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 77916.41
[2024-09-12 21:52:00,629] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 7
step in try: 7
load_mbs: 0.001729726791381836, forward time: 1.237419605255127, backward time: 3.1939587593078613
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 7 done
[2024-09-12 21:53:19,515] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 78885.97
[2024-09-12 21:53:19,516] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 8
step in try: 8
load_mbs: 0.001689910888671875, forward time: 1.2420008182525635, backward time: 3.2039620876312256
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 8 done
[2024-09-12 21:54:43,306] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 83789.62
[2024-09-12 21:54:43,307] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
step: 9
step in try: 9
load_mbs: 0.0016884803771972656, forward time: 1.2423417568206787, backward time: 3.196747303009033
load_mbs cnt: 2, forward cnt: 2, backward cnt: 2
training step: 9 done
[2024-09-12 21:56:07,265] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 83957.37
[2024-09-12 21:56:07,267] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 5.7512 GB | max_mem_allocated: 12.3774 GB | cache_allocated: 14.3828 GB | max_cache_allocated: 14.3828 GB
[2024-09-12 21:56:07,267] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-12 21:56:07,733] [INFO] [engine.py:935:train] Training done.
