[2024-09-12 21:56:38,861] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 0
[2024-09-12 21:56:42,007] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-9-1/mb16.json Launching profiler...
[2024-09-12 21:56:43,916] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:56:47,129] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 0, world_size 9, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:56:48,995] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 21:56:50,010] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 21:57:13,958] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 21:57:17,869] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 21:57:17,870] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 0 iteration
[2024-09-12 21:57:23,261] [INFO] [profiler.py:54:profile_execution_layers] Profiling layer execution latency: 1 iteration
[2024-09-12 21:57:27,990] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 21:57:28,496] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 21:57:28,497] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 21:57:28,497] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 21:57:28,498] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 21:57:28,498] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 9 nodes latency
[2024-09-12 21:57:28,764] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 21:57:28,764] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 21:57:29,902] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.42:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220']
[2024-09-12 21:57:29,902] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 21:57:31,756] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:57:34,941] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 21:57:34,941] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.42:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:57:36,874] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 21:57:37,887] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 9)
min_nodes: 2, max_nodes: 9, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:13] with 1 devices
StageExecutionResult[14:19] with 1 devices
StageExecutionResult[20:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:9] with 1 devices
StageExecutionResult[10:13] with 1 devices
StageExecutionResult[14:17] with 1 devices
StageExecutionResult[18:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:7] with 1 devices
StageExecutionResult[8:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
[2024-09-12 21:57:39,440] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 21:57:39,441] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-12 21:57:39,441] [INFO] [engine.py:739:initialize_distributed] init pg: rank 0, world_size: 9, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-12 21:57:39,441] [INFO] [engine.py:750:initialize_distributed] Creating a TCP store on port: 39573
[2024-09-12 21:57:39,445] [INFO] [agent.py:232:forward_worker_port] Received worker port: 39573 from worker. Forwarding it to master...
[2024-09-12 21:57:39,448] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 21:57:39,448] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 39573 from master
[2024-09-12 21:57:39,616] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 21:57:39,617] [INFO] [engine.py:775:initialize_distributed] [rank: 0] Distributed initialization is done.
[2024-09-12 21:57:39,617] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:57:39,912] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 21:57:39,967] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
Cannot load a SolverResults object with bad status: error
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:57:40,508] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:57:40,711] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:57:40,958] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 21:57:41,233] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.9nodes> pipelines (b: 64)
B: 64
dataloader: mbs 16
[2024-09-12 21:57:47,438] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 21:57:47,439] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.06713318824768066, forward time: 9.68410587310791, backward time: 23.75110411643982
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 0 done
[2024-09-12 21:58:31,295] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 43855.84
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
[2024-09-12 21:58:31,297] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 8.3832 GB | cache_allocated: 9.1152 GB | max_cache_allocated: 9.1152 GB
step: 1
step in try: 1
load_mbs: 0.06421780586242676, forward time: 9.232412099838257, backward time: 23.718526124954224
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 1 done
[2024-09-12 21:59:09,263] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37965.73
[2024-09-12 21:59:09,265] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 2
step in try: 2
load_mbs: 0.0623621940612793, forward time: 9.2195303440094, backward time: 23.71415114402771
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 2 done
[2024-09-12 21:59:47,225] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37959.79
[2024-09-12 21:59:47,226] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 3
step in try: 3
load_mbs: 0.06275629997253418, forward time: 9.225741624832153, backward time: 23.71464776992798
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 3 done
[2024-09-12 22:00:25,178] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37952.25
[2024-09-12 22:00:25,179] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 4
step in try: 4
load_mbs: 0.056943416595458984, forward time: 9.214616775512695, backward time: 23.704795360565186
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 4 done
[2024-09-12 22:01:03,132] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37952.39
[2024-09-12 22:01:03,133] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 5
step in try: 5
load_mbs: 0.055521249771118164, forward time: 9.211268663406372, backward time: 23.70121717453003
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 5 done
[2024-09-12 22:01:41,100] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37967.48
[2024-09-12 22:01:41,102] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 6
step in try: 6
load_mbs: 0.062279462814331055, forward time: 9.220430374145508, backward time: 23.704426288604736
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 6 done
[2024-09-12 22:02:19,055] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37953.70
[2024-09-12 22:02:19,056] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 7
step in try: 7
load_mbs: 0.05930638313293457, forward time: 9.214816331863403, backward time: 23.70060634613037
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 7 done
[2024-09-12 22:02:57,010] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37953.77
[2024-09-12 22:02:57,011] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 8
step in try: 8
load_mbs: 0.06225180625915527, forward time: 9.22009539604187, backward time: 23.70992946624756
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 8 done
[2024-09-12 22:03:34,962] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37950.73
[2024-09-12 22:03:34,963] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
step: 9
step in try: 9
load_mbs: 0.06395459175109863, forward time: 9.218875885009766, backward time: 23.711337089538574
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 9 done
[2024-09-12 22:04:12,912] [INFO] [logging.py:96:log_dist] [Rank 0] time (ms) | step: 37949.10
[2024-09-12 22:04:12,914] [INFO] [logging.py:96:log_dist] [Rank 0]  | mem_allocated: 1.9894 GB | max_mem_allocated: 9.3372 GB | cache_allocated: 10.7559 GB | max_cache_allocated: 10.7559 GB
[2024-09-12 22:04:12,914] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-12 22:04:13,350] [INFO] [engine.py:935:train] Training done.
