[2024-09-12 21:55:02,874] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/workspace/Oobleck/oobleck/__init__.py
node_index: 8
[2024-09-12 21:55:05,923] [WARNING] [agent.py:154:_launch_workers] Profile data for model gpt2 not found. Exception Error parsing json file: /workspace/Oobleck/tmp/profiles/gpt3_1_3B-16-9-1/mb16.json Launching profiler...
[2024-09-12 21:55:07,717] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:55:10,782] [INFO] [profiler.py:270:profile] Profiling model gpt2. rank 8, world_size 9, num_workers_per_node 1.
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:55:12,795] [INFO] [profiler.py:276:profile] Dataset loaded
model_name: gpt2, model_tag: gpt3_1_3B
[2024-09-12 21:55:13,712] [INFO] [profiler.py:284:profile] model loaded
[2024-09-12 21:55:30,691] [INFO] [profiler.py:292:profile] init pg. master_addr: 172.21.0.42, master_port: 23456
[2024-09-12 21:55:41,694] [INFO] [profiler.py:306:profile] Profiling model execution latency.
[2024-09-12 21:55:41,695] [INFO] [profiler.py:112:profile_execution_layers] before barrier
[2024-09-12 21:55:52,320] [INFO] [profiler.py:114:profile_execution_layers] after barrier
[2024-09-12 21:55:52,321] [INFO] [profiler.py:120:profile_execution_layers] before broadcast
[2024-09-12 21:55:52,321] [INFO] [profiler.py:122:profile_execution_layers] after broadcast
[2024-09-12 21:55:52,325] [INFO] [profiler.py:317:profile] Profiling cross-node allreduce latency.
[2024-09-12 21:55:52,325] [INFO] [profiler.py:160:profile_allreduce_across_nodes] Profile allreduce across 9 nodes latency
[2024-09-12 21:55:52,587] [INFO] [profiler.py:326:profile] Profiling in-node allreduce latency.
[2024-09-12 21:55:52,588] [INFO] [profiler.py:209:profile_allreduce_in_node] Profile allreduce within a node latency
[2024-09-12 21:55:53,833] [INFO] [agent.py:189:_launch_workers] in agent. my_ip_port 172.21.0.47:2220, node_ip_ports ['172.21.0.42:2220', '172.21.0.42:2221', '172.21.0.42:2222', '172.21.0.42:2223', '172.21.0.46:2220', '172.21.0.46:2221', '172.21.0.46:2222', '172.21.0.46:2223', '172.21.0.47:2220']
[2024-09-12 21:55:53,833] [INFO] [agent.py:192:_launch_workers] Launching worker 0...
[2024-09-12 21:55:55,715] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-12 21:55:58,758] [INFO] [worker.py:23:worker_main] Initializing Oobleck Engine...
[2024-09-12 21:55:58,758] [INFO] [worker.py:24:worker_main] in worker main: my_ip 172.21.0.47:2220
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1281: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of ðŸ¤— Transformers. Use `use_cpu` instead
  warnings.warn(
Dataset: model_name: gpt2, dataset_path: wikitext, dataset_name: wikitext-2-raw-v1, max_seq_length: 1024
[2024-09-12 21:56:00,693] [INFO] [engine.py:635:_initialize_engine] model arguments: {'n_embd': 2048, 'n_head': 32, 'n_positions': 1024, 'num_hidden_layers': 24}
model_name: gpt2, model_tag: gpt3_1_3B
mb size: 26, ar across: 26, ar in: 26
Loading done. creating layer execution results...
Returning from get_profiler_results
[2024-09-12 21:56:01,598] [INFO] [engine.py:677:_initialize_engine] Number of nodes range: (2, 9)
min_nodes: 2, max_nodes: 9, gpus: 1, 
Create pipeline templates
StageExecutionResult[0:13] with 1 devices
StageExecutionResult[14:25] with 1 devices
StageExecutionResult[0:9] with 1 devices
StageExecutionResult[10:17] with 1 devices
StageExecutionResult[18:25] with 1 devices
StageExecutionResult[0:7] with 1 devices
StageExecutionResult[8:13] with 1 devices
StageExecutionResult[14:19] with 1 devices
StageExecutionResult[20:25] with 1 devices
StageExecutionResult[0:6] with 1 devices
StageExecutionResult[7:11] with 1 devices
StageExecutionResult[12:16] with 1 devices
StageExecutionResult[17:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:5] with 1 devices
StageExecutionResult[6:9] with 1 devices
StageExecutionResult[10:13] with 1 devices
StageExecutionResult[14:17] with 1 devices
StageExecutionResult[18:21] with 1 devices
StageExecutionResult[22:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:8] with 1 devices
StageExecutionResult[9:12] with 1 devices
StageExecutionResult[13:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:4] with 1 devices
StageExecutionResult[5:7] with 1 devices
StageExecutionResult[8:10] with 1 devices
StageExecutionResult[11:13] with 1 devices
StageExecutionResult[14:16] with 1 devices
StageExecutionResult[17:19] with 1 devices
StageExecutionResult[20:22] with 1 devices
StageExecutionResult[23:25] with 1 devices
StageExecutionResult[0:3] with 1 devices
StageExecutionResult[4:6] with 1 devices
StageExecutionResult[7:9] with 1 devices
StageExecutionResult[10:12] with 1 devices
StageExecutionResult[13:15] with 1 devices
StageExecutionResult[16:18] with 1 devices
StageExecutionResult[19:21] with 1 devices
StageExecutionResult[22:23] with 1 devices
StageExecutionResult[24:25] with 1 devices
[2024-09-12 21:56:02,278] [INFO] [worker.py:27:worker_main] Initializing torch.distributed...
[2024-09-12 21:56:02,278] [DEBUG] [engine.py:725:initialize_distributed] regenerate rank_map {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-12 21:56:02,278] [INFO] [engine.py:739:initialize_distributed] init pg: rank 8, world_size: 9, rank_map: {'172.21.0.42:2220': [0], '172.21.0.42:2221': [1], '172.21.0.42:2222': [2], '172.21.0.42:2223': [3], '172.21.0.46:2220': [4], '172.21.0.46:2221': [5], '172.21.0.46:2222': [6], '172.21.0.46:2223': [7], '172.21.0.47:2220': [8]}
[2024-09-12 21:56:02,278] [INFO] [engine.py:755:initialize_distributed] Waiting for a port information...
[2024-09-12 21:56:03,271] [DEBUG] [agent.py:298:on_receive_response] Receiving: (<Response.FORWARD_RANK0_PORT: 5>, <RequestType.UNDEFINED: 0>)
[2024-09-12 21:56:03,272] [DEBUG] [agent.py:243:on_receive_worker_port] agent recv TCP Store port 39573 from master
[2024-09-12 21:56:03,272] [INFO] [engine.py:758:initialize_distributed] Received torch master: 172.21.0.42:2220.39573
[2024-09-12 21:56:03,433] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-09-12 21:56:03,433] [INFO] [engine.py:775:initialize_distributed] [rank: 8] Distributed initialization is done.
[2024-09-12 21:56:03,434] [INFO] [worker.py:34:worker_main] Instantiating pipelines...
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:56:03,766] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
MindtPy initialization may have generated poor quality cuts.
[2024-09-12 21:56:03,817] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
Cannot load a SolverResults object with bad status: error
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:56:04,444] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:56:04,693] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
The objective value -7.4941E-09 of feasibility problem is less than zero_tolerance. This indicates that the nlp subproblem is feasible, although it is found infeasible in the previous step. Check the nlp solver output
[2024-09-12 21:56:04,993] [INFO] [instantiator.py:382:_distribute_batch] Batch distribution find no results. return None
[2024-09-12 21:56:05,345] [INFO] [instantiator.py:256:get_best_execution_plan] Best execution plan: 1 x <oobleck.PipelineTemplate.9nodes> pipelines (b: 64)
B: 64
dataloader: mbs 16
[2024-09-12 21:56:11,261] [INFO] [engine.py:159:_reconfiguration_listener_fn] ReconfigureEngine: start reconfigure listening
[2024-09-12 21:56:11,261] [INFO] [worker.py:36:worker_main] Begin training...
step: 0
step in try: 0
load_mbs: 0.0008339881896972656, forward time: 9.101072072982788, backward time: 16.38240098953247
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 0 done
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:416: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
/root/miniconda3/envs/oobleck/lib/python3.10/site-packages/torch/cuda/memory.py:424: FutureWarning: torch.cuda.max_memory_cached has been renamed to torch.cuda.max_memory_reserved
  warnings.warn(
step: 1
step in try: 1
load_mbs: 0.0007987022399902344, forward time: 8.698832988739014, backward time: 16.42589807510376
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 1 done
step: 2
step in try: 2
load_mbs: 0.0007636547088623047, forward time: 8.697672367095947, backward time: 16.425071954727173
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 2 done
step: 3
step in try: 3
load_mbs: 0.0007605552673339844, forward time: 8.700392723083496, backward time: 16.42289137840271
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 3 done
step: 4
step in try: 4
load_mbs: 0.0007565021514892578, forward time: 8.700847148895264, backward time: 16.423428297042847
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 4 done
step: 5
step in try: 5
load_mbs: 0.0007398128509521484, forward time: 8.699381828308105, backward time: 16.42496681213379
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 5 done
step: 6
step in try: 6
load_mbs: 0.000736236572265625, forward time: 8.698513984680176, backward time: 16.426779747009277
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 6 done
step: 7
step in try: 7
load_mbs: 0.0007503032684326172, forward time: 8.696883916854858, backward time: 16.427518129348755
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 7 done
step: 8
step in try: 8
load_mbs: 0.0007181167602539062, forward time: 8.695763111114502, backward time: 16.426336526870728
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 8 done
step: 9
step in try: 9
load_mbs: 0.0007274150848388672, forward time: 8.695297241210938, backward time: 16.42373824119568
load_mbs cnt: 64, forward cnt: 64, backward cnt: 64
training step: 9 done
[2024-09-12 22:02:33,854] [INFO] [engine.py:932:train] Training is done. Waiting for synchronization...
[2024-09-12 22:02:37,175] [INFO] [engine.py:935:train] Training done.
